version: "3.8"
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # создаём таблицы БД
      - ./data.sql:/docker-entrypoint-initdb.d/load_data.sql # загружаем данные в таблицы
      - ./quest.sql:/docker-entrypoint-initdb.d/queries.sql # выполняем запросы к БД
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "username", "library_db"]
      interval: 5s
      retries: 5
    restart: always